exam fullstack
sh4rkizz/2022-2-VK-EDU-FS-Frontend-A-Mahonin pull request #10
Opened 2022-12-29 17:06 UTC by sh4rkizz

# Экзамен

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* Пока
* Работа
* В
* Процессе)

2022-12-29 18:31 UTC, martinkomitsky commented on exam/src/Molecules/LangSwitchRow/LangSwitchRow.jsx
> +  })
[]

2022-12-29 23:13 UTC, sh4rkizz commented
https://sh4rkizz.github.io/2022-2-VK-EDU-FS-Frontend-A-Mahonin/

2022-12-29 23:14 UTC, sh4rkizz commented on exam/src/Molecules/LangSwitchRow/LangSwitchRow.jsx
> +  })
fixed

2022-12-30 18:21 UTC, martinkomitsky requested changes
Что-то не понимаю, как сделать перевод(((
Не нашел фичу для перевода с конкретного языка на желаемый
+ ещё есть ошибка
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/14847018/210100976-1d1e9ee4-02c3-4649-a983-748815823d86.png">

2022-12-31 11:02 UTC, sh4rkizz commented
fixed dead translations (added localstorage check)
added start language feature

2022-12-31 11:53 UTC, martinkomitsky approved these changes
ура, теперь всё!
40
Можешь сдать еще домашку-две для получения 5

2022-12-31 11:53 UTC, merged