Homework #3
sh4rkizz/2022-2-VK-EDU-FS-Frontend-A-Mahonin pull request #4
Opened 2022-10-23 20:58 UTC by sh4rkizz

# Домашнее задание № 3

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* Реализована страница со списком чатов
* При обновлении или обратном переходе на страницу чатов происходит автообновление списка по данным из локального хранилища (сортировка по времени)
* Реализован переход на страницу часа с использованием query-параметра `id`
* Реализована декомпозиция на отдельные блоки

2022-10-24 19:21 UTC, HaseProgram approved these changes
Засчитано, но надо разобраться с роутингом, сейчас клики по чатам ведут в 404, так как теряется половина адреса

2022-10-24 19:24 UTC, HaseProgram requested changes
А нет, я поспешил, тут незарезолвленые конфликты, надо исправить

2022-10-25 21:19 UTC, sh4rkizz commented
Привет, пофиксил падающие миграции, вырубил использование статической директории, добавив на их место плейсхолдер

2022-10-27 11:03 UTC, HaseProgram approved these changes
12!

2022-10-27 11:27 UTC, merged