Homework 8-9
sh4rkizz/2022-2-VK-EDU-FS-Frontend-A-Mahonin pull request #9
Opened 2022-12-12 02:52 UTC by sh4rkizz

# Домашнее задание № 8-9

Прошу @martinkomitsky или @haseprogram проверить его и заранее извиняюсь за две сразу.

Доброго времени суток, как говорят представители МГТС перерубившие интрернет нашему подъезду 9 часов назад :3
По работе:
* Теперь мой код это теперь куча мелких функций, аж **самому читать приятно стало**
* Реализована `отправка фотографий в base64` (я не стесняюсь поэтому фотка моя)))
* У картиночек есть превью, которое вырубается (удаляется из сообщения) нажатием на него
* Реализована `отправка аудиозаписей`, я там пою, честно-честно (пока реализовал не самый красивый способ сказать пользователю о том, что его прослушивают, позже обновлю)
* Спалил свой дом на `геолокации`, которая пока отправляется в виде текстовой ссылки, позже докину превью ссылок
* Пока без логики (то есть нелогично) реализованы `некоторые из оставшихся пейджей`, которые можно глянуть по урлам из app.js
* Запилил `нереальный новый продукт` `ультрасуперсовременный` react-redux (юзал `тулкит`, потому что он красивый)
* `Не восстанавливал` работоспособность общего чата после нововведений (но могу, если попросите), поскольку у меня бэк прокачанный
* `С 10 домашкой возникли проблемы` в процессе из-за бекенда, дня через два допилю
## Ну и по традиции, видос с функционалом
#### Тестим ГС
![textVoice](https://user-images.githubusercontent.com/70894081/206948957-dda59d7f-6d40-4911-aac6-5c652c4e8984.gif)
#### Тестим фоточки и геолокацию
![textGeoAndPhoto](https://user-images.githubusercontent.com/70894081/206950379-5240232a-b365-4297-9c3b-c3d511eb21b5.gif)

2022-12-12 15:12 UTC, martinkomitsky requested changes
Для начала починить ошибки бы
https://github.com/sh4rkizz/2022-2-VK-EDU-FS-Frontend-A-Mahonin/actions/runs/3672108348/jobs/6207978594

2022-12-12 15:19 UTC, martinkomitsky commented on react-messenger/src/slices/activeChat.js
> +export default activeChatSlice.reducer
зочем? кто придумал чат в стор закидывать???

2022-12-12 16:26 UTC, sh4rkizz commented on react-messenger/src/slices/activeChat.js
> +export default activeChatSlice.reducer
я придумал и в реализации 10ой уже убрал, идея была не супер гуд, хотел через стор замутить уведомления

2022-12-13 20:20 UTC, sh4rkizz commented
Неслабо `порефакторил` ~свою страхолюдину~ свой код, существенно уменьшив количество запросов при поллинге, как прикручу к беку вебсокеты, так вообще буду супер доволен собою
Also `фиксанул варнинги`, роняющие GP
have a nice day)

2022-12-14 11:36 UTC, martinkomitsky requested changes
Поставлю за 8 и 9 дз 10 баллов за старания, но вот с 10 надо еще повозиться.
Сейчас могу спокойно переходить по страницам, в определенный момент получаю какой-то странный экран с 404, еще непонятно, как попасть на экран логина.

Я обновил описание ДЗ10, см. в него.
Жду правки и видео с демо 10 ДЗ

2022-12-24 15:22 UTC, martinkomitsky commented
@sh4rkizz, привет! Будут ли еще фиксы?

2022-12-28 22:21 UTC, sh4rkizz commented
К сожалению придется пропустить 10ую в счет 11ой и 12ой домашки на данный момент, иначе не успею до экзамена их доделать, с Auth`ом возникли некоторые проблемы из-за несовершенства бекенда, доделаю 10 до глобального додлайна

2022-12-29 14:26 UTC, sh4rkizz commented
## Не фоточка, но на ней красоточка, я заставил все таки работать логин, немного доработав код.
#### Тест логина (теперь работает для любого аккаунта из списка, я `победил автологин усердием и грубой силой`). До логина юзеру путь в систему заказан, можно даже не пытаться, хотя, непрошенный гость может поглядеть на красивую (нет) страницу `Not Found`
![testLogin](https://user-images.githubusercontent.com/70894081/209965488-ef0b215a-37ed-4846-8310-800a27439251.gif)
#### Тест логаута, выход осуществляется через страницу настройки, нажатием на красную кнопку Logout
![testLogout](https://user-images.githubusercontent.com/70894081/209965618-e6d664b8-fb14-46c5-8d16-00c075571218.gif)

2022-12-30 15:06 UTC, martinkomitsky approved these changes
12

2022-12-30 15:06 UTC, merged